version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9400:8080"
      - "9401:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=production

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9500:3000"
    environment:
    - ORIGIN=http://localhost:9500
    depends_on: [api]
