version: "3.8"

name: lctracker-dev

services:
  pg:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - dev_pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_HOST_PORT}:${PG_CONTAINER_PORT}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "9480:8080"

volumes:
  dev_pgdata: