version: "3.8"

services:
  server:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - ${SERVER_HOST_HTTP_PORT}:${SERVER_CONTAINER_HTTP_PORT}
      - ${SERVER_HOST_HTTPS_PORT}:${SERVER_CONTAINER_HTTPS_PORT}
    environment:
      - ASPNETCORE_ENVIRONMENT=${SERVER_ENVIRONMENT}
    depends_on: [pg]

  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - VITE_PUBLIC_API_URL=http://server:${SERVER_CONTAINER_HTTP_PORT}
    ports:
      - ${WEB_HOST_HTTP_PORT}:${WEB_CONTAINER_HTTP_PORT}
    environment:
      - ORIGIN=${WEB_ORIGIN}
    depends_on: [server]

  pg:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "9432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "9480:8080"

volumes:
  pgdata: