version: "3.8"

services:
  server:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - ${SERVER_HOST_HTTP_PORT}:${SERVER_CONTAINER_HTTP_PORT}
      - ${SERVER_HOST_HTTPS_PORT}:${SERVER_CONTAINER_HTTPS_PORT}
    environment:
      - ASPNETCORE_ENVIRONMENT=${SERVER_ENVIRONMENT}

  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - VITE_PUBLIC_API_URL=http://server:${SERVER_CONTAINER_HTTP_PORT}
    ports:
      - ${WEB_HOST_HTTP_PORT}:${WEB_CONTAINER_HTTP_PORT}
    environment:
      - ORIGIN=${WEB_ORIGIN}
    depends_on: [server]
